In [1]:
import pandas as pd
import numpy as np

In [2]:
n_obs = 1000

theta1 = np.array([[1., 2., 4.], [-3., -2., 4.]])
theta2 = np.array([5., -3., 4.])
cst = -3.

m = np.random.random(size=(n_obs, 3))

x = np.random.random(size=n_obs)

noise = np.random.normal(0, 0.001, size=(n_obs, 3))
noise2 = np.random.normal(0, 0.002, size=n_obs)

m = np.zeros((n_obs, 3))
for j in range(3):
    m[:, j] = theta1[0, j] + x * theta1[1, j] + noise[:, j]

y = np.zeros(n_obs) + cst + noise2
for j in range(3):
    y[:] += m[:, j] * theta2[j] 

In [3]:
x 

array([3.84790065e-01, 1.91742906e-01, 7.07018052e-01, 8.01544238e-02,
       7.67020757e-01, 7.09760966e-02, 9.00107019e-02, 8.74125742e-01,
       7.42810503e-02, 9.55967935e-01, 4.80101424e-01, 6.14927701e-01,
       3.86857954e-01, 4.38464131e-01, 1.33809834e-01, 6.70747297e-01,
       5.67058287e-01, 7.83582659e-01, 5.99949707e-01, 2.92770733e-01,
       8.46663805e-01, 8.93922904e-01, 4.40811536e-01, 7.05711035e-01,
       2.06541361e-01, 7.60451865e-01, 3.08524054e-02, 3.23508677e-01,
       5.40217698e-01, 3.13743648e-01, 9.76776506e-01, 4.98271774e-01,
       2.16619024e-01, 7.97666297e-01, 7.02526213e-01, 8.33683133e-01,
       9.34896746e-01, 3.45848466e-01, 4.41843227e-01, 8.94940069e-01,
       5.91821190e-01, 6.95231955e-01, 2.53287525e-01, 4.47587678e-01,
       6.67600833e-01, 4.84465233e-01, 3.78203334e-02, 2.94109030e-01,
       1.15629731e-01, 1.72198033e-01, 2.61207132e-01, 4.82659529e-01,
       7.49435945e-01, 5.51085137e-01, 7.44582150e-01, 9.49116163e-01,
      

In [4]:
y

array([14.69855697, 13.34385091, 16.96352641, 12.56544051, 17.36042942,
       12.48704673, 12.64227539, 18.13331749, 12.51406823, 18.70645282,
       15.36670671, 16.30919455, 14.71844304, 15.05178921, 12.93336968,
       16.68791436, 15.97371823, 17.48453779, 16.19551801, 14.04215747,
       17.91437071, 18.25895969, 15.08370808, 16.95619978, 13.43867138,
       17.32806609, 12.22575545, 14.27454475, 15.78146634, 14.20341251,
       18.84566584, 15.48978347, 13.51383896, 17.58760981, 16.92444092,
       17.84861915, 18.54470033, 14.41386313, 15.08901849, 18.27954736,
       16.13632834, 16.86259735, 13.78084795, 15.11593039, 16.66635818,
       15.3933469 , 12.26395334, 14.05325107, 12.81147784, 13.20247134,
       13.82537784, 15.37512211, 17.2383455 , 15.85805918, 17.213986  ,
       18.64610192, 13.73080005, 14.57638741, 13.2634961 , 13.30440391,
       18.03205264, 12.9865    , 18.36681989, 13.36215471, 17.77874483,
       14.65394941, 15.91479006, 15.68991129, 15.82017505, 18.70

In [5]:
m

array([[-0.15485224,  1.23003034,  5.54064808],
       [ 0.42538944,  1.61601706,  4.76728604],
       [-1.12092541,  0.58416647,  6.82970644],
       ...,
       [ 0.23773821,  1.48954553,  5.02006833],
       [-1.31095913,  0.45833648,  7.0793731 ],
       [-1.53329096,  0.30994424,  7.37979084]])

In [6]:
h, m, e = m[:, 0], m[:, 1], m[:, 2]

In [7]:
h

array([-1.54852240e-01,  4.25389440e-01, -1.12092541e+00,  7.60644833e-01,
       -1.30207515e+00,  7.86546182e-01,  7.31241474e-01, -1.62029813e+00,
        7.77848969e-01, -1.86605874e+00, -4.39865000e-01, -8.44724934e-01,
       -1.60404848e-01, -3.17373686e-01,  5.99596739e-01, -1.01330950e+00,
       -7.01807562e-01, -1.35108247e+00, -8.00326021e-01,  1.22196285e-01,
       -1.54065417e+00, -1.68199083e+00, -3.21398331e-01, -1.11608773e+00,
        3.79651368e-01, -1.28112366e+00,  9.08795473e-01,  3.02212518e-02,
       -6.20315730e-01,  5.85951707e-02, -1.93095899e+00, -4.94922170e-01,
        3.50246666e-01, -1.39281174e+00, -1.10747508e+00, -1.49974267e+00,
       -1.80443304e+00, -3.75293659e-02, -3.25688409e-01, -1.68255666e+00,
       -7.75897538e-01, -1.08436911e+00,  2.40234172e-01, -3.44256386e-01,
       -1.00372461e+00, -4.53565795e-01,  8.86896592e-01,  1.17933932e-01,
        6.53539357e-01,  4.84300580e-01,  2.16843342e-01, -4.48999980e-01,
       -1.24829302e+00, -

In [8]:
df = pd.DataFrame(dict(x=x, y=y, m=m, h=h, e=e))

In [9]:
df.to_csv('fake.csv', index=False)