In [69]:
import numpy as np
import pandas as pd
import semopy

In [9]:
np.random.seed(0)
n = 30
x = np.random.random(n)
y = 2. * x + 3.

In [33]:
X = x.reshape((-1,1 ))
X = np.hstack((X, np.ones_like(X)))

In [34]:
X

array([[0.5488135 , 1.        ],
       [0.71518937, 1.        ],
       [0.60276338, 1.        ],
       [0.54488318, 1.        ],
       [0.4236548 , 1.        ],
       [0.64589411, 1.        ],
       [0.43758721, 1.        ],
       [0.891773  , 1.        ],
       [0.96366276, 1.        ],
       [0.38344152, 1.        ],
       [0.79172504, 1.        ],
       [0.52889492, 1.        ],
       [0.56804456, 1.        ],
       [0.92559664, 1.        ],
       [0.07103606, 1.        ],
       [0.0871293 , 1.        ],
       [0.0202184 , 1.        ],
       [0.83261985, 1.        ],
       [0.77815675, 1.        ],
       [0.87001215, 1.        ],
       [0.97861834, 1.        ],
       [0.79915856, 1.        ],
       [0.46147936, 1.        ],
       [0.78052918, 1.        ],
       [0.11827443, 1.        ],
       [0.63992102, 1.        ],
       [0.14335329, 1.        ],
       [0.94466892, 1.        ],
       [0.52184832, 1.        ],
       [0.41466194, 1.        ]])

$b =  (X^T X)^{-1}  X^T y$

http://mlwiki.org/index.php/Normal_Equation

In [37]:
np.linalg.inv(X.T@X)@X.T@y

array([2., 3.])

In [58]:
data = pd.read_csv('worland5.csv')
data

motiv       harm      stabi     ppsych        ses     verbal  \
0    -7.907122  -5.075312  -3.138836 -17.800210   4.766450  -3.633360   
1     1.751478  -4.155847   3.520752   7.009367  -6.048681  -7.693461   
2    14.472570  -4.540677   4.070600  23.734260 -16.970670  -3.909941   
3    -1.165421  -5.668406   2.600437   1.493158   1.396363  21.409450   
4    -4.222899 -10.072150  -6.030737  -5.985864 -18.376400  -1.438816   
..         ...        ...        ...        ...        ...        ...   
495   3.274111   6.335590   7.966526 -22.634070  -3.404731   4.002903   
496   2.871656   3.414905  10.560660  -3.599253   8.025676  -6.791690   
497   2.577785   2.078503  -5.524660   5.369411  -5.751442   0.860869   
498  15.158430  20.210650   8.040233  -1.093764  -8.675011 -12.160090   
499 -17.682350 -20.886040 -13.443200   5.205892 -10.634370  -9.503462   

          read      arith      spell  
0    -3.488981  -9.989121  -6.567873  
1    -4.520552   8.196238   8.778973  
2    -4.818170   7.529984  -5.688716  
3    -3.138441   5.730547  -2.915676  
4    -2.009742  -0.623953  -1.024624  
..         ...        ...        ...  
495   6.263109  -4.254130  -0.432311  
496  12.249790   4.475929   8.856446  
497   7.032958  -3.787138   1.084259  
498   3.888996  -0.185587   0.872260  
499 -19.837630 -23.932320 -21.334100  

[500 rows x 9 columns]

In [59]:
data.cov()

motiv       harm       stabi     ppsych        ses     verbal  \
motiv   100.000003  77.000002   59.000002 -25.000001  24.999998  32.000001   
harm     77.000002  99.999999   58.000001 -24.999998  25.999998  25.000000   
stabi    59.000002  58.000001  100.000004 -16.000000  17.999999  27.000000   
ppsych  -25.000001 -24.999998  -16.000000  99.999995 -41.999998 -39.999999   
ses      24.999998  25.999998   17.999999 -41.999998  99.999998  39.999999   
verbal   32.000001  25.000000   27.000000 -39.999999  39.999999  99.999999   
read     53.000002  42.000000   36.000003 -38.999998  43.000000  56.000001   
arith    60.000002  44.000001   38.000001 -24.000000  36.999998  49.000001   
spell    59.000002  45.000000   38.000004 -30.999999  32.999999  48.000000   

              read       arith       spell  
motiv    53.000002   60.000002   59.000002  
harm     42.000000   44.000001   45.000000  
stabi    36.000003   38.000001   38.000004  
ppsych  -38.999998  -24.000000  -30.999999  
ses      43.000000   36.999998   32.999999  
verbal   56.000001   49.000001   48.000000  
read    100.000002   73.000002   87.000001  
arith    73.000002  100.000002   72.000002  
spell    87.000001   72.000002  100.000000

In [63]:
motiv = data['motiv'].values
motiv

array([-7.907122e+00,  1.751478e+00,  1.447257e+01, -1.165421e+00,
       -4.222899e+00,  4.868769e+00,  1.036737e+01, -1.861007e+00,
       -1.345222e+01,  2.852636e+00, -2.135480e+00, -1.327171e+01,
        7.468200e-02, -1.234672e+00,  1.621586e+01,  2.627465e+00,
       -2.094704e+01,  1.803133e+00, -2.228813e+00,  1.455498e+01,
        4.125528e+00,  2.618851e+01, -1.465615e+00, -6.474650e-01,
       -1.897242e+01,  4.559503e+00, -3.140967e+00,  3.014924e+00,
       -2.370748e+00,  5.418550e+00,  8.727378e+00, -7.142818e+00,
       -1.858579e+01, -1.271571e+01,  2.989872e+00, -8.942353e+00,
        1.060920e+01,  1.979164e+01,  2.792732e+00, -2.337454e+00,
       -1.016219e+01,  1.418544e+01,  4.504490e-01, -7.736377e+00,
       -1.616346e+01, -1.527247e+01,  7.318634e+00,  9.711668e+00,
        1.529264e+01,  6.868947e+00,  5.639946e+00,  5.475866e+00,
        4.200402e+00,  4.692285e+00, -1.804298e+00,  1.208730e+01,
       -4.530589e+00,  1.406372e+01,  1.280981e+01, -1.367006e

In [67]:
X = motiv.reshape((-1, 1))
X = np.hstack((X, np.ones_like(X)))
y = data['read'].values

In [68]:
np.linalg.inv(X.T@X)@X.T@y

array([ 5.300e-01, -1.232e-07])

In [93]:
desc = "read ~ motiv\nmotiv~~motiv"

# mod = semopy.Model(desc)
mod = semopy.ModelMeans(desc)

# choose from: MLW
# Choose from: L-BFGS-B, SLSQP, BFGS
# nlminb "adaptive nonlinear least-squares algorithm".
res = mod.fit(data, obj='ML', solver='SLSQP')
print(res)
print(mod.inspect())


Name of objective: FIML
Optimization method: SLSQP
Optimization successful.
Optimization terminated successfully
Objective value: 5438.291
Number of iterations: 11
Params: -0.000 -0.000 0.530 99.800 71.766
    lval  op   rval   Estimate  Std. Err    z-value   p-value
0   read   ~  motiv   0.530017  0.037923  13.975959  0.000000
1  motiv   ~      1  -0.000039  0.446766  -0.000087  0.999931
2   read   ~      1  -0.000118  0.378855  -0.000311  0.999752
3  motiv  ~~  motiv  99.800005  6.311907  15.811388  0.000000
4   read  ~~   read  71.765618  4.538856  15.811388  0.000000


In [91]:
desc = \
    "read ~ ppsych + motiv" + "\n" + \
    "arith ~ motiv"

# mod = semopy.Model(desc)
mod = semopy.Model(desc)

In [92]:
mod.parameters

{'_b1': Model.Parameter(start=None, active=True, bound=(None, None), locations=[Model.ParameterLoc(matrix=array([[0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 1.]]), indices=(1, 1), symmetric=False)]),
 '_b2': Model.Parameter(start=None, active=True, bound=(None, None), locations=[Model.ParameterLoc(matrix=array([[0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 1.]]), indices=(1, 0), symmetric=False)]),
 '_b3': Model.Parameter(start=None, active=True, bound=(None, None), locations=[Model.ParameterLoc(matrix=array([[0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 1.]]), indices=(0, 0), symmetric=False)]),
 '_c1': Model.Parameter(start=None, active=False, bound=(0, None), locations=[Model.ParameterLoc(matrix=array([[0., 0.],
        [0., 0.]]), indices=(0, 0), symmetric=False)]),
 '_c2': Model.Parameter(start=None, active=False, bound=(None, None), locations=[Model.ParameterLoc(matrix=array([[0., 0.],
        [0., 0.]]), indices=(0, 1), symmetric=True)]),

In [87]:
mod.matrices_names

('beta', 'lambda', 'psi', 'theta')

In [88]:
mod.mx_lambda

array([[ 0.60000018,  0.        ],
       [ 0.46133278, -0.27466722],
       [ 1.        ,  0.        ],
       [ 0.        ,  1.        ]])

In [89]:
mod.mx_psi

array([[ 99.80000307, -24.95000055],
       [-24.95000055,  99.79999506]])

In [90]:
mod.mx_theta

array([[63.86901298,  0.        ,  0.        ,  0.        ],
       [ 0.        , 64.70404932,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [85]:
mod.mx_beta

array([[0., 0.],
       [0., 0.]])

In [82]:
# choose from: MLW
# Choose from: L-BFGS-B, SLSQP, BFGS
# nlminb "adaptive nonlinear least-squares algorithm".
res = mod.fit(data, obj='MLW', solver='SLSQP')
print(res)
print(mod.inspect())

Name of objective: MLW
Optimization method: SLSQP
Optimization successful.
Optimization terminated successfully
Objective value: 0.470
Number of iterations: 13
Params: -0.275 0.461 0.600 64.704 63.869
    lval  op    rval   Estimate  Std. Err    z-value       p-value
0   read   ~  ppsych  -0.274667  0.037190  -7.385451  1.518785e-13
1   read   ~   motiv   0.461333  0.037190  12.404650  0.000000e+00
2  arith   ~   motiv   0.600000  0.035776  16.770907  0.000000e+00
3   read  ~~    read  64.704049  4.092243  15.811388  0.000000e+00
4  arith  ~~   arith  63.869013  4.039431  15.811388  0.000000e+00


In [79]:
print(mod.vars)

{'all': {'arith', 'read', 'motiv', 'ppsych'}, 'endogenous': {'read', 'arith'}, 'exogenous': set(), 'observed': ['arith', 'read'], 'latent': set(), 'indicator': set(), 'output': {}, 'observed_exogenous': ['1', 'motiv', 'ppsych'], '_output': {'read', 'arith'}, 'inner': [], 'observed_exogenous_1': set(), 'observed_exogenous_2': {'1', 'motiv', 'ppsych'}}
